repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v1.7.0
#    hooks:
#    - id: autopep8
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
#-   repo: https://github.com/pycqa/flake8
#    rev: '5.0.4'  # pick a git hash / tag to point to
#    hooks:
#    -   id: flake8
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=pylintrc", # Link to your config file
          "--load-plugins=pylint.extensions.docparams", # Load an extension
        ]
