# ================================================================
# Workbench instance information
# ================================================================
workbench:
    description: Galaxy instance
    fqdn: galaxy.workbench.com
    user: ubuntu
    password: "passw0rd"
    ssh_key: ~/identity.pem
    root_path: /opt/workbench/compose
    api_client_key: mykey
    api_client_secret: "LKAJHSKJAKJKHAKJSH"

auth:
    basic_auth: True
